abs_datapath: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/Scenewalk_python/DATA"

datasets:
  spst_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/SpatStat/npy"
  spst_training: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/SpatStat/split_sets/training/"
  spst_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/SpatStat/split_sets/test/"
  corpus_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/corpusData/split_sets/test/"
  corpus_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/corpusData/npy_unclean"
  corpus_training: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/corpusData/split_sets/training/"
  mbody1_q1: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q1/all/"
  mbody1_q1_train: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q1/train/"
  mbody1_q2: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q2/all/"
  mbody1_q3: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q3/all/"
  mbody1_q4: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q4/all/"
  mbodyfied_spst: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/SpatStat/mbodyfied"
  mit_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MIT1003/npy"
  mit_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MIT1003/test"
  mit_train: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MIT1003/train"
  mbody1_q1_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q1/test/"
  mbody1_q2_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q2/test/"
  mbody1_q3_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q3/test/"
  mbody1_q4_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q4/test/"
  mbody1_q1_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q1/all/"
  mbody1_q2_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q2/all/"
  mbody1_q3_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q3/all/"
  mbody1_q4_all: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/SceneWalk_research/DATA/MBody1/npy_q4/all/"