abs_datapath: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/Scenewalk_python/DATA"

datasets:
  spst_training: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/Scenewalk_python/DATA/SpatStat/split_sets/training/"
  spst_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/Scenewalk_python/DATA/SpatStat/split_sets/test/"
  corpus_test: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/Scenewalk_python/DATA/corpusData/split_sets/test/"
  corpus_training: "/Users/lisa/Documents/SFB1294_B05/SceneWalk/Scenewalk_python/DATA/corpusData/split_sets/training/"

